Remove unused 'not_supported' function.
Found by compiling under GCC 6.  The warning was:

In file included from libvirt_c.c:2058:0:
libvirt_c_epilogue.c:89:1: error: 'not_supported' defined but not used [-Werror=unused-function]
 not_supported (const char *fn)
 ^~~~~~~~~~~~~